config/routes.rb
TrackApp::Application.routes.draw do
  get "data_points/new"
  devise_for :users

  root 'static_pages#index'

  resources :goals, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :datapoints
  end

  

end

app/models/datapoint.rb
class Datapoint < ActiveRecord::Base
  belongs_to :goal
  validates :goal, presence: true
  validates :date, presence: true
end

app/models/goal.rb
class EitherWeekly < ActiveModel::Validator
	def validate(goal)
		if goal.weekly_quantity.present? && goal.weekly_frequency.present?
			goal.errors[:weekly_frequency] << "cannot be set if weekly_quantity is set"
			goal.errors[:weekly_quantity] << "cannot be set if weekly_frequency is set"
		end
	end
end

class Goal < ActiveRecord::Base
	belongs_to :user, inverse_of: :goals
	has_many :datapoints, :dependent => :destroy
	accepts_nested_attributes_for :datapoints, :reject_if => :all_blank, :allow_destroy => true
	validates :weekly_frequency, numericality: true, allow_blank: true
	validates :weekly_quantity, numericality: true, allow_blank: true
	validates :weight, numericality: true, allow_blank: false
	validates_with EitherWeekly

	def last_week_of_data
		last_week = Date.today - 7
		recent_data = self.datapoints.where(date: last_week..Date.today)
		total_this_week = 0
		recent_data.each do |point|
			total_this_week += point.amount
		end
		total_this_week
	end

	def met_this_week?
		if self.weekly_quantity.present?
			return self.last_week_of_data >= self.weekly_quantity
		else
			return self.last_week_of_data >= self.weekly_frequency
		end
	end

	def gap
		if self.weekly_quantity.present?
			return self.weekly_quantity - self.last_week_of_data
		else
			return self.weekly_frequency - self.last_week_of_data
		end
	end

	def target_score
		if self.weekly_quantity.present?
			return self.weekly_quantity*self.weight
		else
			return self.weekly_frequency*self.weight
		end
	end

	class << self
		def score (user)
			running_score = 0
			user.goals.each do |goal|
				running_score += goal.last_week_of_data*goal.weight
			end
			running_score
		end

		def target_score (user)
			target = 0
			user.goals.each do |goal|
				if goal.weekly_frequency.present?
        	target += goal.weekly_frequency*goal.weight
      	else
        	target += goal.weekly_quantity*goal.weight
      	end
			end
			target
		end

		def bonus_score (user)
			bonus = score(user) - target_score(user)
			if bonus > 0
				bonus
			else
				0
			end
		end

	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many 	:goals,
  					inverse_of: :user,
  					dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/datapoints_controller.rb
class DatapointsController < ApplicationController
  before_action :set_datapoint, only: [:show, :edit, :update, :destroy]
  before_action :set_goal, only: [:new, :create]

  # GET /datapoints
  # GET /datapoints.json
  def index
    @datapoints = Datapoint.all
  end

  # GET /datapoints/1
  # GET /datapoints/1.json
  def show
  end

  # GET /datapoints/new
  def new
    @datapoint = @goal.datapoints.new
  end

  # GET /datapoints/1/edit
  def edit
    @datapoint = Datapoint.find(params[:id])
    @goal = @datapoint.goal
  end

  # POST /datapoints
  # POST /datapoints.json
  def create
    @datapoint = @goal.datapoints.new(datapoint_params)

    respond_to do |format|
      if @datapoint.save
        format.html { redirect_to goal_path(@goal), notice: 'Datapoint was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /datapoints/1
  # PATCH/PUT /datapoints/1.json
  def update
    respond_to do |format|
      if @datapoint.update(datapoint_params)
        format.html { redirect_to @datapoint, notice: 'Datapoint was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @datapoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datapoints/1
  # DELETE /datapoints/1.json
  def destroy
    @datapoint.destroy
    respond_to do |format|
      format.html { redirect_to datapoints_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_datapoint
      @datapoint = Datapoint.find(params[:id])
    end

    def set_goal
      @goal = current_user.goals.find(params[:goal_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def datapoint_params
      params.require(:datapoint).permit(:amount, :date)
    end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
	before_filter :authenticate_user!


	def index
		@goals = current_user.goals
	end

	def new
		@goal = Goal.new
	end

	def create
		@goal = current_user.goals.new(goals_params)
		if @goal.save
			flash[:notice] = "Goal created"
			redirect_to @goal
		else
			render "new"
		end
	end

	def show
		@goal = current_user.goals.find(goal_params[:id])
	end

	def edit
		@goal = current_user.goals.find(goal_params[:id])
	end

	def update
		@goal = current_user.goals.find(goal_params[:id])
		respond_to do |format|
			if @goal.update(goals_params)
				format.html { redirect_to goal_path(@goal), notice: "Goal was updated" }
			else
				format.html { render 'edit' }
			end
		end
	end

	def destroy
		Goal.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to goals_path }
    end
	end

	private

	def goals_params
		params.require(:goal).permit(:objective, :weekly_frequency, :weekly_quantity, :weight,
			datapoints_attributes: [:id, :date, :amount, :_destroy])
	end

	def goal_params
		params.permit(:id)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_points_helper.rb
module DataPointsHelper
end

app/helpers/datapoints_helper.rb
module DatapointsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/datapoints/_datapoint_fields.html.erb
  <div class="nested-fields">
    <%= f.input :amount, label: "amount" %>
    <%= f.input :date, label: "date" %>
    <%= link_to_remove_association "remove data", f %>
  </div>

app/views/datapoints/_form.html.erb
<%= simple_form_for(@datapoint) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :goal_id %>
    <%= f.input :amount %>
    <%= f.input :date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/datapoints/edit.html.erb
<h1>Editing datapoint</h1>

<%= simple_form_for [@goal, @datapoint] do |form| %>
  <%= form.input :amount %>
  <%= form.input :date %>
  <%= form.button :submit, label: "submit" %>
<%- end %>

<%= link_to 'Back', goal_path(@goal) %>

app/views/datapoints/index.html.erb
<h1>Listing datapoints</h1>

<table>
  <thead>
    <tr>
      <th>Goal</th>
      <th>Amount</th>
      <th>Date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @datapoints.each do |datapoint| %>
      <tr>
        <td><%= datapoint.goal_id %></td>
        <td><%= datapoint.amount %></td>
        <td><%= datapoint.date %></td>
        <td><%= link_to 'Show', datapoint %></td>
        <td><%= link_to 'Edit', edit_datapoint_path(datapoint) %></td>
        <td><%= link_to 'Destroy', datapoint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Datapoint', new_datapoint_path %>

app/views/datapoints/new.html.erb
<h1>New datapoint</h1>

<%= simple_form_for [@goal, @datapoint] do |form| %>
  <%= form.input :amount %>
  <%= form.input :date %>
  <%= form.button :submit, label: "submit" %>
<%- end %>

<%= simple_form_for @goal do |f| %>
  <%= f.simple_fields_for :datapoints do |builder| %>
    <%= render 'datapoint_fields', :f => builder %>
    <div class="links">
      <%= link_to_add_association 'add data', f, :datapoints %>
    </div>
  <% end %>
  <%= f.submit "Submit" %>
<% end %>

<%= link_to 'Back', goal_path(@goal) %>

app/views/datapoints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Goal:</strong>
  <%= @datapoint.goal_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @datapoint.amount %>
</p>

<p>
  <strong>Date:</strong>
  <%= @datapoint.date %>
</p>

app/views/goals/_datapoint_fields.html.erb
  <div class="nested-fields row">
    <div class="span3">
      <%= f.label :amount, nil%>
      <%= f.text_field :amount %>
    </div>
    <div class="span3">
      <%= f.label :date, nil%>
       <%= f.date_field :date %>
    </div>
    <div class="span2">
      <%= link_to_remove_association "remove data", f, html_options = {class: "btn btn-small"} %>
    </div>
  </div>

app/views/goals/edit.html.erb
<h1>Update goal</h1>


<%= simple_form_for(@goal) do |form| %>
  <%= form.input :objective %>
  <%= form.input :weekly_frequency %>
  <%= form.input :weekly_quantity %>
  <%= form.input :weight, default: 1.0 %>
  <%= form.button :submit %>
<% end %>

<%= link_to 'Back', goal_path(@goal) %>

app/views/goals/index.html.erb
<%= link_to('Create new goal', new_goal_path) %>

<h3>Goals</h3>
<ul>
  <%- @goals.each do |goal| %>
    <li>
      <%= link_to "%{goal}" % {:goal => goal.objective}, goal_path(goal) %>
      <% if goal.weekly_frequency.present? %>
        <% unit = "times" %>
        <% amount = goal.weekly_frequency %>
      <% else %>
        <% unit = "minutes" %>
        <% amount = goal.weekly_quantity %>
      <% end %>
      <%= "#{goal.last_week_of_data}/#{amount} #{unit} this week 
          (#{goal.last_week_of_data*goal.weight}/#{goal.target_score} points)" %>
    </li>
  <%- end %>
</ul>

<%= "Your score today is #{Goal.score(current_user)}" %>
<p>
<%= "Your target score is #{Goal.target_score(current_user)}" %>
</p>
<%= "You have a bonus of #{Goal.bonus_score(current_user)}" %>

app/views/goals/new.html.erb
<%= simple_form_for @goal do |form| %>
	<%= form.input :objective %>
	<%= form.input :weekly_frequency %>
	<%= form.input :weekly_quantity %>
  <%= form.input :weight, default: 1.0%>
	<%= form.button :submit %>
<%- end %>

<%= link_to "Home", root_path %>
<%= link_to "Back", goals_path %>

app/views/goals/show.html.erb
<% freq = @goal.weekly_frequency.present? %>
<% if freq %>
  <% unit = "times" %>
<% else %>
  <% unit = "minutes" %>
<% end %>
<h1><%= @goal.objective %></h1>
<center><%- if freq %>
  <%= "#{@goal.weekly_frequency} times a week" %>
<%- else %>
  <%= "#{@goal.weekly_quantity} minutes per week" %>
<%- end %>
<p>
<font size="1"><%= "(worth #{@goal.weight} points)" %></font>
</p>
</center>
<h4>Datapoints</h4>

<%= form_for @goal, class: "form-inline" do |f| %>
  <div id="datapoints">
    <%= f.fields_for :datapoints do |builder| %>
      <%= render 'datapoint_fields', :f => builder %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'add data', f, :datapoints %>
     </div>
  </div>
  <%= f.submit "Submit" %>
<% end %>

<h4><%= "Your total so far this week is: #{@goal.last_week_of_data}" %>
<p>
<% if @goal.met_this_week? %>
  <%= "You have met your goal this week" %>
<% else %>
  <%= "You need to #{@goal.objective} #{@goal.gap} #{unit} today to meet your goal" %>
<% end %>
</p>
</h4>
<%= link_to "Edit goal", edit_goal_path(@goal) %>
<%= button_to "Destroy goal", goal_path(@goal), method: :delete, data: { confirm: "Delete this goal?" }  %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Track App
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Your goals", goals_path %></li>
      <li><%= link_to "Create new goal", new_goal_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Track App", '#'%>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if current_user.present? %>
            <li><%= "Signed in as #{current_user.email}" %></li>
            <li><%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>          
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrackApp</title>
    <%= stylesheet_link_tag    "application", media: "all"%>
    <%= javascript_include_tag "application"%>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>

  </body>
</html>

app/views/static_pages/index.html.erb
<div class="center">
  <h3>Welcome to Track App</h3>

  Keep track of your goals, get a score.

  <h4><%= link_to "View Your Goals", goals_path %></h4>
</div>